x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/root/.nanobot
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  nanobot-personal:
    container_name: nanobot-personal
    <<: *common-config
    network_mode: host
    command: ["gateway", "-w", "/workspace", "-c", "/root/.nanobot/personal-config.json", "-p", "18790"]
    restart: unless-stopped
    volumes:
      - ~/.nanobot:/root/.nanobot
      - ~/.nanobot/personal_workspace:/workspace
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  nanobot-group:
    container_name: nanobot-group
    <<: *common-config
    network_mode: host
    command: ["gateway", "-w", "/workspace", "-c", "/root/.nanobot/group-config.json", "-p", "18791"]
    restart: unless-stopped
    volumes:
      - ~/.nanobot:/root/.nanobot
      - ~/.nanobot/group_workspace:/workspace
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
